services:
  gitlab:
    platform: linux/amd64
    image: ${GITLAB_IMAGE:-gitlab/gitlab-ee}:${GITLAB_VERSION:-latest}
    container_name: ${DEPLOYMENT_NAME:-gitlab-external-db}-gitlab
    hostname: 'gitlab.local'
    restart: unless-stopped
    ports:
      - '${HTTP_PORT:-8080}:80'
      - '${HTTPS_PORT:-8443}:443'
      - '${SSH_PORT:-2222}:22'
    volumes:
      - './config/gitlab.rb:/etc/gitlab/gitlab.rb:ro'
      - 'config-vol:/etc/gitlab'
      - 'logs-vol:/var/log/gitlab'
      - 'data-vol:/var/opt/gitlab'
    shm_size: '256m'
    healthcheck:
      test: ["CMD", "/opt/gitlab/bin/gitlab-healthcheck", "--fail", "--silence-deprecation"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 120s
    depends_on:
      - postgres
      - redis
    networks:
      - gitlab_network

  postgres:
    platform: linux/amd64
    image: ${POSTGRES_IMAGE:-postgres}:${POSTGRES_VERSION:-13}
    container_name: ${DEPLOYMENT_NAME:-gitlab-external-db}-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: gitlab
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-gitlab_password}
      POSTGRES_DB: gitlabhq_production
    volumes:
      - 'postgres-data:/var/lib/postgresql/data'
    ports:
      - '${POSTGRES_PORT:-5432}:5432'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U gitlab"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    networks:
      - gitlab_network

  redis:
    platform: linux/amd64
    image: ${REDIS_IMAGE:-redis}:${REDIS_VERSION:-6.2-alpine}
    container_name: ${DEPLOYMENT_NAME:-gitlab-external-db}-redis
    restart: unless-stopped
    command: redis-server --requirepass ${REDIS_PASSWORD:-redis_password}
    volumes:
      - 'redis-data:/data'
    ports:
      - '${REDIS_PORT:-6379}:6379'
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    networks:
      - gitlab_network

networks:
  gitlab_network:
    name: ${DEPLOYMENT_NAME:-gitlab-external-db}-network

volumes:
  config-vol:
    name: ${DEPLOYMENT_NAME:-gitlab-external-db}-config
  logs-vol:
    name: ${DEPLOYMENT_NAME:-gitlab-external-db}-logs
  data-vol:
    name: ${DEPLOYMENT_NAME:-gitlab-external-db}-data
  postgres-data:
    name: ${DEPLOYMENT_NAME:-gitlab-external-db}-postgres-data
  redis-data:
    name: ${DEPLOYMENT_NAME:-gitlab-external-db}-redis-data
