concurrent = 2
check_interval = 0

[session_server]
  session_timeout = 1800

[[runners]]
  name = "Shell Runner"
  url = "http://runners-gitlab.local"
  token = "glrt-xxxxxxxxxxxxxxxxxxxx"
  executor = "shell"
  shell = "bash"
  [runners.cache]
    [runners.cache.s3]
    [runners.cache.gcs]